name: Feature
on:
  push:
    branches:
      - "feature/*"
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan

  create-pull-request:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create Pull Request
        run: gh pr create -B main --title "Merge ${GITHUB_REF#refs/heads/} with main" --body "Created by Github Action"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
